name: naayu_attire1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  local_auth: ^2.2.0
  shared_preferences: ^2.2.2   

  cupertino_icons: ^1.0.8
  test_cov_console: ^0.2.2

  # Local Database (Sprint 3)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Clean Architecture helpers
  permission_handler: ^12.0.1   # âœ… keep this one
  equatable: ^2.0.5
  dartz: ^0.10.1

  # State management
  provider: ^6.1.2

  # UUID
  uuid: ^4.4.0

  # Media
  image_picker: ^1.0.7
  video_player: ^2.8.2 

  # Networking (Sprint 4 - API)
  dio: ^5.4.1
  connectivity_plus: ^6.0.5
  http: ^1.2.0

  geolocator: ^10.1.0
  geocoding: ^2.1.0
  google_maps_flutter: ^2.5.0

  webview_flutter: ^4.4.2
  url_launcher: ^6.3.0
  fl_chart: ^0.66.0

  # PDF generation
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.2  

   # Date formatting (for invoice date, etc.)
  intl: ^0.19.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/home/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/videos/hero.mp4
    - assets/images/splash/
    - assets/images/casual/
    - assets/images/coord/
    - assets/images/wedding/
    - assets/images/party/
    - assets/images/onepiece/
    - assets/images/winter/
    - assets/images/about/
    - assets/images/tryon/
    - assets/images/banners/
    

