name: naayu_attire1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2   

  cupertino_icons: ^1.0.8

  # Local Database (Sprint 3)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Clean Architecture helpers
  permission_handler: ^12.0.1
  equatable: ^2.0.5
  dartz: ^0.10.1

  # State management
  provider: ^6.1.2

  # UUID
  uuid: ^4.4.0

  # Media
  image_picker: ^1.0.7

  # Networking (Sprint 4 - API)
  dio: ^5.4.1
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
